version: "3.9"

services:
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
  web:
    build: .
    command: ./starter
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      - db
